version: '3.8'
services:
  cache:
    container_name: redis
    image: redis:7.0.0
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  cache:
    driver: local